name = "worker-auth"
main = "src/index.ts"
compatibility_date = "2022-10-07"
kv_namespaces = [
  {binding = "USERS", id = "bd445a5887f6437cb4ec9adb11a19106", preview_id = "bd445a5887f6437cb4ec9adb11a19106"},
]
[vars]
ONE_HOUR = 3600
ONE_DAY = 86400
